### ISSUE TITLE
after first click it doesnt work

### ISSUE THREAD

**Issue by 1Euro7Cent** [danielchang2002/MinesweeperBot#1]
Got this error:
![image](https://user-images.githubusercontent.com/67194495/126908137-70c89bcd-ec0f-4ea5-a004-a98ad5371f98.png)
 for info: I saw that you are using not windows. I use it.

**Comment by danielchang2002** [comment]
Yes, I think this issue is due to windows/macos differences. On line 15, 16 and 21, 22, comment out the code that multiplies the coordinates by 2

**Comment by 1Euro7Cent** [comment]
Now it clicks not in the right positions (more at the top left) like it should be multiplied by 2

**Comment by danielchang2002** [comment]
That's strange. I don't have a windows machine to test this on, but I would try to use pyautogui.position() to see if there are issues with how pyautogui reads mouse positions
