### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by Timothy2105** [danielchang2002/MinesweeperBot#3]
The program, when run, seems to not be running the "getNonTrivial" function, as it is never called. Also, the bot constantly sets the value of board.move() to true and never fills out the board before resetting it.

Link to video of the bug:
(https://user-images.githubusercontent.com/110699285/183219128-01815f54-e9e0-4e13-b7a8-bd9f1fcdc39e.webm)

**Comment by danielchang2002** [comment]
I believe the issue is occurring because your version of minesweeper generates the board before you click the first cell. Because of this, sometimes after you click the first cell, no other cells are also opened because the cell you clicked has a nonzero number of bombs around it. Hope that helps!
